### ISSUE TITLE
[FEATURE REQUEST]: OTP programming - ABIRES and Zero Position

### ISSUE THREAD

**Issue by MatejsLab** [jonas-merkle/AS5047P#44]
**Is your feature request related to a problem? Please describe.**
I used Adrien's library, but I looked into yours also, both libraries are missing the programming of the OTP memory.

**Describe the solution you'd like**
I got a request at a project job to write code for sensor AS5047P, the code, for now, runs on Arduino Uno.
They wish to configure the sensor and make it permanent, I ask for your help to make it work.
They need to write ABIRES and Zero Position to the sensor and program the OTP, so the sensor remembers the settings.
They want to read absolute position over ABI interface, for that they use their gear.

**Describe alternatives you've considered**
I used Adrien's library to configure sensor settings which worked fine, but I was unable to program OTP register.
I also tried to pass raw commands to the sensor, it looked like it worked, but it seems like the sensor didn't remember its settings after the power cycle.

**Additional context**
I followed this datasheet for programming OTP https://ams.com/documents/20143/36005/AS5047P_DS000324_3-00.pdf
It looks like I got something wrong, but I can't figure out what the bug is.

It would be awesome if you would be able to test this code and maybe find out the bug by next week's Thursday 2.2.23.
If possible you can tweak my code to make it work.

It would be great if your library could support OTP programming natively but it seems like the commands for the PROG register refused to pass into the sensor.

Here is the code I wrote, it has a serial interface for some configuration.

[ConfigureSensor_AS5074_MK_V1.10.zip](https://github.com/Adrien-Legrand/AS5X47/files/10521753/ConfigureSensor_AS5074_MK_V1.10.zip)

Thanks a lot, in advance.
Matej

**Comment by jonas-merkle** [comment]
Hello Matej,

I would really like to help you solve your problem, but it's not easy to do so quickly. I don't know the AS5X47.h library well enough to evaluate your software in detail. My library does not officially support the writing of OTP registers but the basic functions are implemented (namely: [`write_PROG `](https://github.com/jonas-merkle/AS5047P/blob/466d9b5e8dd714c5bb441902c035ef17c3b8a31a/src/AS5047P.h#L246) & [`write_SETTINGS1`](https://github.com/jonas-merkle/AS5047P/blob/466d9b5e8dd714c5bb441902c035ef17c3b8a31a/src/AS5047P.h#L324)). But I have never tested this functionality, because I don't have a sensor where I could reprogram the OTP registers.
We can try to implement a software for writing OTP registers based on these functions. I can't guarantee that it will work without problems and the testing (including the risk that something goes wrong) would have to be done by you.

Best regards
Jonas

**Comment by MatejsLab** [comment]
Actually, i found out that the code i wrote does work, but i accidentally powered the sensor with 5V instead of 3.3V, it did work but fail to write OTP, on 3.3V it actually worked. Thanks for the response, i only struggle to reliably detect if the sensor is connected based on reading error flags, that sometimes show 0 as OK, and not 1 as ERR. Could i probe SPI directly, any ideas appreciated.

**Comment by jonas-merkle** [comment]
Hi @MatejsLab 
Glad to hear you got your first problem solved. 😄 
I'm just not quite sure if I understood your new problem correctly.... tldr: you sometimes have "connection problems" with the sensor and want to find out via reading the error register if the sensor is connected correctly?
While I was using the sensor I also had connection problems with the sensor from time to time. In my case it was basically always due to one of the following two problems:

1. the sensor sometimes seems to react a bit sensitive to not 100% correct wiring (e.g. when the sensor is connected to the Arduino on a breadboard).
2. if the Arduino is reset, but the sensor is not, the SPI communication gets corrupted. As a result, it is no longer possible to communicate properly with the sensor until it has gone through a power cycle or is reset.

In itself it is no problem to access the sensor manually via SPI and to read registers. Whether this would help you in troubleshooting I don't know. Because then you can only recognize, the sensor answers and the library does not work or the sensor does not answer at all. If you have a logic analyzer at hand you can listen to the SPI communication from outside and check if timings are kept and the sensor responds or if your Arduino already does not send reasonable data to the sensor.

**Comment by MatejsLab** [comment]
Thanks for sharing your experience, i codded in control of the the power to
sensor with arduino, so that arduino can reset sensor.

I appriciate your help, the customer confirmed that the programmer works
fine now.

Lp Matej Kotnik

V sob., 18. feb. 2023 17:26 je oseba Jonas Merkle [JJM] <
***@***.***> napisala:
